# Generated by Django 5.2.12 on 2026-05-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
