# Generated by Django 5.2.15 on 2026-08-24 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_fornecedor_telefone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacoes_ativas', models.BooleanField(default=True, help_text='Exibir alertas de estoque na barra superior', verbose_name='Notificações de estoque ativas')),
                ('notificar_sem_estoque', models.BooleanField(default=True, verbose_name='Alertas de produtos sem estoque')),
                ('notificar_estoque_baixo', models.BooleanField(default=True, verbose_name='Alertas de produtos com estoque baixo')),
                ('relatorios_resumo', models.BooleanField(default=True, verbose_name='Exibir métricas automáticas no painel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
